[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.6.0"

[[constraint]]
  name = "zvelo.io/go-zapi"
  version = "0.0.2"

[[constraint]]
  name = "zvelo.io/msg"
  version = "~1.3.0"
